### ISSUE TITLE
skip_routes not working for Laravel 8.x

### ISSUE THREAD

**Issue by weayzehoa** [littlebookboy/laravel-request-recorder#1]
在 Laravel 8.x 裡使用 skip_routes 會造成http code 500錯誤.
測試後發現修改 RequestRecorderMiddleware.php 如下即可正常運作.

        // 使用者在 config 中有匹配到目前請求路由，進入檢查 http code 的設定
        if (array_key_exists($routeName, $skipRoutes->toArray())) {
            $dataSet = $skipRoutes->get($routeName)->first();

            // 當 config 中對應該路由的 http code 的設定為空或萬用，所有對應該請求的路由都記錄起來
            if (empty($dataSet['http_code']) || in_array('*', $dataSet['http_code'])) {
                return true;
            }
            if (in_array($responseCode, $dataSet['http_code'])) {
                return true;
            }
        }

        // // 使用者在 config 中有匹配到目前請求路由，進入檢查 http code 的設定
        // if (array_key_exists($routeName, $skipRoutes->toArray())) {
        //     $dataSet = $skipRoutes->get($routeName)->first();

        //     // 當 config 中對應該路由的 http code 的設定為空或萬用，所有對應該請求的路由都記錄起來
        //     if (empty(array_get($dataSet, 'http_code')) || in_array('*', array_get($dataSet, 'http_code'))) {
        //         return true;
        //     }

        //     if (in_array($responseCode, array_get($dataSet, 'http_code'))) {
        //         return true;
        //     }
        // }

**Comment by littlebookboy** [comment]
你好，如果需求僅是要能支援 Laravel 8.x 的話，
我個人做法會替換 Helper 方法為 8.x 所支援的做法，改使用 ` Arr::get()`；

或者因為 Laravel 5.6 以前的 Arr 與 Laravel 8.x 的 Arr 屬於不同類別，會需要另外判斷版本的情況下，只要保留 php 寫法會相對比較通用，但須注意原本設計是可以避免 config skip_routes 未設置正確的情況，如果直接取 http_code 索引，可能會拋出例外。

```
    ...
    
    // 未設置 http_code 時，表示該路由所有 response code 皆不寫紀錄
    if (!isset($dataSet['http_code']) || empty($dataSet['http_code'])) { 
        return true;
    }

    // 有設置 http_code，且直接設置為 * 時，表示該路由所有 response code 皆不寫紀錄
    // 不設定 = 設定 *
    if (is_array($dataSet['http_code']) && in_array('*', $dataSet['http_code'])) { 
        return true;
    }
    if (is_string($dataSet['http_code']) && '*' === $dataSet['http_code']) { 
        return true;
    }

    // 有設置 http_code，且非為 *，表示該路由符合指定的 response code 時，不寫紀錄
    if (is_array($dataSet['http_code']) && in_array($responseCode, $dataSet['http_code'])) {
        return true;
    }
    if (is_string($dataSet['http_code']) && $responseCode === $dataSet['http_code']) { 
        return true;
    }
}
```

**Comment by weayzehoa** [comment]
感謝您的回復, 我重新修改了一份, 不依賴 Laravel 版本的作法, 並增加判斷 $data['http_code'] 是否為陣列, 避免設定錯誤.
另外有碰到 response_content 過長問題, 順便修改 migration 的欄位為 longText.

**Comment by littlebookboy** [comment]
已更新 v1.4，看看是否能正常使用；
另外不建議使用本套件用於生產環境，目前是沒有 test 保護，加上這只是練習性質的專案，感謝。

**Comment by weayzehoa** [comment]
非常感謝您. 您的這套件真的不錯.
